# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.discovery.spire.enabled }}
apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: {{ include "runtime.discovery.fullname" . }}
spec:
  className: {{ .Values.discovery.spire.className }}
  podSelector:
    matchLabels:
      {{- include "runtime.discovery.selectorLabels" . | nindent 6 }}
  workloadSelectorTemplates:
    - k8s:sa:{{ include "runtime.discovery.serviceAccountName" . }}
  spiffeIDTemplate: {{ "spiffe://{{ .TrustDomain }}/ns/{{ .PodMeta.Namespace }}/sa/{{ .PodSpec.ServiceAccountName }}" }}
  autoPopulateDNSNames: true
{{- end }}
